### ISSUE TITLE
image component

### ISSUE THREAD

**Issue by ericyliu** [palmetto/palmetto-components#108]
possible component we want to copy the functionality of or just straight up use: https://github.com/stereobooster/react-ideal-image

Features
1. src should extrapolate to srcset (or straight up take in a srcset string[])
2. aspect ratio
3. width/height
4. loading state

**Comment by juanfabrega** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Image Component](https://trello.com/c/drgpgAT2/874-image-component)
