### ISSUE TITLE
Remove need for duplicate Interface + PropType declarations to generate storybook docs.

### ISSUE THREAD

**Issue by juanfabrega** [palmetto/palmetto-components#123]

**Comment by nathanyoung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Babel plugin for generating proptypes](https://trello.com/c/P8q8slu8/138-babel-plugin-for-generating-proptypes)

**Comment by nathanyoung** [comment]
https://storybook.js.org/docs/configurations/typescript-config/

**Comment by juanfabrega** [comment]
This is addressed in the bundling changes that now generate proptypes from typescript interfaces.
