### ISSUE TITLE
Bundling revisited!

### ISSUE THREAD

**Issue by juanfabrega** [palmetto/palmetto-components#124]
Unify build process between storybook and distrbution.

* Ensure CSS bundling/minifying, etc etc.

**Comment by nathanyoung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bundling Revisited!](https://trello.com/c/ndQgW6ih/139-bundling-revisited)

**Comment by juanfabrega** [comment]
Addressed here https://github.com/palmetto/palmetto-components/pull/148
