### ISSUE TITLE
Date Input

### ISSUE THREAD

**Issue by nathanyoung** [palmetto/palmetto-components#137]
A single component that:

- allows selection of only date
- allows selection of only time
- allows selection of date AND time
- the input matches the TextInput and SelectInput on initial appearance
- mobile optimized

A common use case for this component(s) would be to allow a user to select a date and time for an appointment.

ToDo:
- [x] Determine what solution is currently being used for Logistics app.

- [ ] Determine what solution is currently being used for Home app.

- [ ] Determine general design concepts regarding look and layout.

- [ ] Determine features/props that will be supported.

**Comment by nathanyoung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [DateTime Input](https://trello.com/c/yURVDWbr/145-datetime-input)

**Comment by nathanyoung** [comment]
https://projects.wojtekmaj.pl/react-datetimerange-picker/
https://reactdatepicker.com/
https://jquense.github.io/react-widgets/api/DateTimePicker/

**Comment by JCarmine** [comment]
Logistics app is currently using flatpickr for a date picker. Both dropdown and inline modes are supported.

For the time picker, logistics is using a custom dropdown. SelectorInput should be used for this feature if it should remain separate from date picker. flatpicker actually supports selecting a time in addition to the date, but the UX is poor.

<img width="494" alt="Screen Shot 2020-07-27 at 2 17 04 PM" src="https://user-images.githubusercontent.com/5695990/88610584-e90fdc00-d03b-11ea-8c72-e4a09f978a84.png">
<img width="320" alt="Screen Shot 2020-07-27 at 2 43 20 PM" src="https://user-images.githubusercontent.com/5695990/88610590-ea410900-d03b-11ea-913f-f0817e062fc2.png">
<img width="550" alt="Screen Shot 2020-07-27 at 3 03 01 PM" src="https://user-images.githubusercontent.com/5695990/88610591-ead99f80-d03b-11ea-8a55-0f503ce52c42.png">

**Comment by nathanyoung** [comment]
date picker component added to components library.

https://github.com/palmetto/palmetto-components/pull/318
