### ISSUE TITLE
Input Component

### ISSUE THREAD

**Issue by juanfabrega** [palmetto/palmetto-components#14]
We need a controlled input component. It should expose all standard input properties and events to the consumer, while maintaining a consistent aesthetic, matching this:

![Screen Shot 2020-06-30 at 9 54 46 AM](https://user-images.githubusercontent.com/19932356/86134649-e57a4b00-bab7-11ea-993f-0874af56cb9e.png)

**NOT REQUIRED BUT NICE TO HAVE FOR MVP**
* Input masking (for phone number format for example)

**Comment by nathanyoung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Input Component](https://trello.com/c/7z6sNNbp/42-input-component)

**Comment by juanfabrega** [comment]
PR: https://github.com/palmetto/palmetto-components/pull/16

PENDING: Tests.
