### ISSUE TITLE
Normalize Component CSS

### ISSUE THREAD

**Issue by JCarmine** [palmetto/palmetto-components#142]
See #3: https://blog.newrelic.com/engineering/best-practices-shared-ui-libraries/

Article suggests normalizing at the component level, as opposed to using a global reset. This would suggest wrapping each component in a "paper" or container component which would have the styles applied to it, or using composes from CSS Modules. This way, each module has its own reset, but the consuming app can override if they choose to do so.

**Comment by JCarmine** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Normalize ](https://trello.com/c/YVKU63R7/140-normalize)

**Comment by juanfabrega** [comment]
PR with proposal here: https://github.com/palmetto/palmetto-components/pull/202
