### ISSUE TITLE
Consumer styles are cascading to Palmetto components, impacting alignment

### ISSUE THREAD

**Issue by nathanyoung** [palmetto/palmetto-components#145]
<img width="805" alt="Screen Shot 2020-07-28 at 4 47 42 PM" src="https://user-images.githubusercontent.com/1447339/88741011-6a767580-d0f3-11ea-9604-60010aba8252.png">

In the above example, another framework (bootstrap) is applying a margin bottom to all `<label>` elements. Since our `<FormLabel />` does not have a margin property, it is inheriting the margin set by bootstrap.

**Comment by juanfabrega** [comment]
@nathanyoung I am not sure if this addresses the specific issue with bootstrap, but in the latest iteration of in `develop` branch I merged a change as part of the css-modules branch where our labels would not in fact add extra margin to the inputs and instead the inputs would add it to the label. This would hopefully make boostrap's `label` selector redundant, but, again I have yet to try it in practice.

**Comment by nathanyoung** [comment]
@juanfabrega i don't think that address the specific issue above. The css selector used by bootstrap applies to all labels, so unless we specify a margin value, it's going to cascade and get applied.

<img width="439" alt="Screen Shot 2020-07-28 at 5 10 06 PM" src="https://user-images.githubusercontent.com/1447339/88741727-40be4e00-d0f5-11ea-9961-7af0b3085004.png">

**Comment by nathanyoung** [comment]
<img width="432" alt="Screen Shot 2020-07-28 at 5 11 38 PM" src="https://user-images.githubusercontent.com/1447339/88741787-68adb180-d0f5-11ea-8e81-aa9254c0f95a.png">

**Comment by juanfabrega** [comment]
Gotcha, makes sense!
