### ISSUE TITLE
TS is Stripping Trailing "OneOfType" Types from Storybook Docs

### ISSUE THREAD

**Issue by JCarmine** [palmetto/palmetto-components#150]
In the following example, declaring `label: React.ReactNode | string;` in the interface will result in the following output in Storybook, leading the consumer to believe that the prop only accepts a node.

<img width="1017" alt="Screen Shot 2020-08-03 at 3 19 46 PM" src="https://user-images.githubusercontent.com/5695990/89237207-7193fc80-d5a7-11ea-9ea4-0961466e48c0.png">

**Comment by juanfabrega** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Typescript props not matching proptypes](https://trello.com/c/tpqjnpuE/164-typescript-props-not-matching-proptypes)
