### ISSUE TITLE
Allow SelectInput's selected value to be cleared

### ISSUE THREAD

**Issue by nickj-rp** [palmetto/palmetto-components#160]
I need to be able to clear the selected value on a <SelectInput> component that does not have multi-select enabled.

We should just be able to pass the `isClearable` prop through to the underlying react-select component.

**Comment by juanfabrega** [comment]
This works. I’ll draft a PR to expose more of our underlying react-select
props for use.

**Comment by nickj-rp** [comment]
Many thanks!

**Comment by juanfabrega** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Clear SelectInput](https://trello.com/c/SDPp8D1v/166-clear-selectinput)

**Comment by juanfabrega** [comment]
Open PR is here: https://github.com/palmetto/palmetto-components/pull/165

**Comment by juanfabrega** [comment]
Hey @nickj-rp this has been merged and released in [release 0.2.0](https://github.com/palmetto/palmetto-components/releases/tag/v0.2.0)

Note I have already updated this dependency in the `logistics-platform` repo`master` branch as well.
