### ISSUE TITLE
Some of the Greys are a Little Green.

### ISSUE THREAD

**Issue by JCarmine** [palmetto/palmetto-components#166]
For e.g. `--color-brand-grey-lightest`

**Comment by juanfabrega** [comment]
@nathanyoung just wanted to make sure you saw this. I am seeing the same thing. very apparent in the table, where we use grey-lightest.

**Comment by nathanyoung** [comment]
The grey is meant to be a little green, not simply neutral greys. I want the greys to be on the warm side. As we get into more use cases, I can reduce the level of green if we find it's too much. 

Still yet to be determined if we should offer zebra striping for the table.
