### ISSUE TITLE
Checkbox Component

### ISSUE THREAD

**Issue by juanfabrega** [palmetto/palmetto-components#17]
We need a controlled checkbox component. It should expose all standard checkbox properties and events to the consumer, while maintaining a consistent aesthetic, matching this:

<img width="284" alt="Screen Shot 2020-06-30 at 2 46 01 PM" src="https://user-images.githubusercontent.com/19932356/86164855-7402c280-bae0-11ea-85fb-5d5a7e6bdb99.png">

**Comment by nathanyoung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Checkbox Input](https://trello.com/c/k8m4LNnB/48-checkbox-input)

**Comment by nathanyoung** [comment]
https://github.com/palmetto/palmetto-components/pull/66
