### ISSUE TITLE
Update `master` branch to `main`

### ISSUE THREAD

**Issue by juanfabrega** [palmetto/palmetto-components#216]
Update any corresponding yml files to maintain workflows.

**Comment by nathanyoung** [comment]
https://github.com/palmetto/palmetto-components/pulls

**Comment by nathanyoung** [comment]
https://github.com/palmetto/palmetto-components/pull/237

**Comment by nathanyoung** [comment]
https://github.com/palmetto/palmetto-components/pull/237
