### ISSUE TITLE
normalize and or reset css.

### ISSUE THREAD

**Issue by nathanyoung** [palmetto/palmetto-components#22]
We have started a `reset.css` file, but should we just use normalize?

https://github.com/necolas/normalize.css

**Comment by juanfabrega** [comment]
@nathanyoung yes, this is my go-to as well. Let's get other's thoughts but it should be quick and easy.

**Comment by juanfabrega** [comment]
Closed, should have an answer to this after discussion is done on https://github.com/palmetto/palmetto-components/issues/95

**Comment by nathanyoung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Normalize ](https://trello.com/c/YVKU63R7/140-normalize)
