### ISSUE TITLE
Convert repo to typescript

### ISSUE THREAD

**Issue by ericyliu** [palmetto/palmetto-components#25]
can use rollup plugins after https://github.com/palmetto/palmetto-components/pull/24 is merged

1. https://github.com/rollup/plugins (babel and typescript)

2. connect typescript types and proptypes: https://github.com/milesj/babel-plugin-typescript-to-proptypes
  - comments can be transpiled too https://github.com/milesj/babel-plugin-typescript-to-proptypes#comments-boolean

**Comment by nathanyoung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Convert Palmetto Components to Typescript](https://trello.com/c/c1IwUCf3/79-convert-palmetto-components-to-typescript)
