### ISSUE TITLE
Box borderWidth prop type definition

### ISSUE THREAD

**Issue by nathanyoung** [palmetto/palmetto-components#291]
Passing a css shorthand (top, left, bottom, right) style value to borderWidth results in a typescript error.

Functionally this still works (applies a top border), but build will fail because of `type-check`

<img width="699" alt="Screen Shot 2020-10-21 at 6 32 57 PM" src="https://user-images.githubusercontent.com/1447339/96807701-19151400-13cc-11eb-9a42-db5a8a5b0148.png">

**Comment by nathanyoung** [comment]
repro in the `modal` branch: https://github.com/palmetto/palmetto-components/blob/modal/src/components/Modal/Modal.tsx#L95

**Comment by juanfabrega** [comment]
https://github.com/palmetto/palmetto-components/pull/292
