### ISSUE TITLE
SelectInput dropdown styles are impacted by parent container

### ISSUE THREAD

**Issue by nathanyoung** [palmetto/palmetto-components#328]
CSS properties that we aren't explicitly setting in the SelectInput css are being inherited by the parent, for example in this screenshot, in the SelectInput's dropdown, the text size is 'lg' and is `textAlign: center` rather than 'md' and left aligned. 

<img width="484" alt="Screen Shot 2020-11-09 at 3 40 30 PM" src="https://user-images.githubusercontent.com/1447339/98609364-f5920a80-22a1-11eb-9eb9-79613f28f691.png">

Expected:
Prevent parent container styles from polluting the select dropdown's styles.

**Comment by juanfabrega** [comment]
@nathanyoung would like to add something else I found here which is that the hover/selected states don't seem to come from our library and don't match our token colors. That light blue I believe is from react-select.
