### ISSUE TITLE
Could we add additional masks to the TextInput?

### ISSUE THREAD

**Issue by JCarmine** [palmetto/palmetto-components#339]
Two additional useful masks would be:
1) Number (just adds commas)
2) Currency

**Comment by osbornm** [comment]
Some opinions / thoughts on this: 

- Currency is just `number` with a prefix (when dealing with U.S. currency)
- Can be done today but _seems_ reasonable to add it as one of the [known types](https://github.com/palmetto/palmetto-components/blob/main/src/components/TextInput/TextInputMasks.js). 

here is an example of how to do it without code changes: 
https://codesandbox.io/s/little-bird-20x9o?file=/src/App.js

**Comment by nathanyoung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add Number (adds commas) mask to TextInput](https://trello.com/c/eeHrLG0L/690-add-number-adds-commas-mask-to-textinput)

**Comment by juanfabrega** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add additional masks to textinput](https://trello.com/c/9sxrmbtO/875-add-additional-masks-to-textinput)
