### ISSUE TITLE
Select component doesn't support autofill

### ISSUE THREAD

**Issue by mtblanton** [palmetto/palmetto-components#347]
See https://github.com/JedWatson/react-select/issues/1397

Adding a select component that doesn't use react-selet would be preferred, but other solutions are also welcome!

**Comment by nathanyoung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Styled browser/system select component alternative to react-select](https://trello.com/c/btrlfhgC/435-styled-browser-system-select-component-alternative-to-react-select)

**Comment by juanfabrega** [comment]
This should be addressed by the addition of a `SelectInputNative` component which just uses a standard HTML select under the hood as opposed to react-select

https://github.com/palmetto/palmetto-components/pull/436
