### ISSUE TITLE
Cursor displays in DateInput, but nothing can be entered

### ISSUE THREAD

**Issue by JCarmine** [palmetto/palmetto-components#357]
It seems correct that nothing can be entered, forcing the user to interact with the calendar. However, there are two UX issues resulting from this:

1) Even though nothing can be directly entered, the cursor still flashes, leading the user to think that it could.
2) On mobile, focusing on DateInput will prompt the mobile keyboard to open, which obscures the calendar. Since nothing can be directly entered, the keyboard popping just makes the feature more difficult to use.

**A possible solution:** Adding the `readonly` attribute to the input.

![2020_12_08_13 15 41](https://user-images.githubusercontent.com/5695990/101545481-2a09ec80-395c-11eb-92f8-4d67e78a7789.jpg)

**Comment by juanfabrega** [comment]
@JCarmine just an FYI that we have pulled this issue into our current sprint on the UX side.

**Comment by nathanyoung** [comment]
related: https://github.com/palmetto/palmetto-components/issues/376

**Comment by juanfabrega** [comment]
https://github.com/palmetto/palmetto-components/pull/419
