### ISSUE TITLE
Modify `radius` prop for Box to accept CSS shorthand

### ISSUE THREAD

**Issue by JCarmine** [palmetto/palmetto-components#370]
As it is now, the single value provided to `radius` is applied universally to all four corners. It might be beneficial to update this so that it can also accept a string, similar to CSS shorthand. So: `radius="md md 0 0"`.

We have found a workaround by just doing: `style={{ borderRadius: '8px 8px 0 0' }}`, so this feature is nothing urgent.

**Comment by nathanyoung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Modify `radius` prop for Box to accept responsive CSS shorthand](https://trello.com/c/RXBK0Cdp/434-modify-radius-prop-for-box-to-accept-responsive-css-shorthand)
