### ISSUE TITLE
Adapt <FileUpload> Display for Mobile

### ISSUE THREAD

**Issue by JCarmine** [palmetto/palmetto-components#377]
Not sure if this is a bug, or even feature that we want. But, in the following screenshot we have the file upload button and helpText side-by-side on a 320px device. As can be seen, the button gets quite tall given its content's length. 

In cases like this, it might be nice to make the button a block level element so that it spans the full width of the container, and the help text displays below it. 

I attempted using the `fullWidth` prop as the docs say "Pass the fullWidth prop to have your FileUpload button take up the entire width of its container.", but it had no effect. After reviewing palmetto-components, it appears that the button and its helpText are held in a container fixed to `row`.

Also attached, a rough proposed fix:

Current:
![Screen Shot 2021-01-06 at 5 57 07 PM](https://user-images.githubusercontent.com/5695990/103842935-c272ba00-504b-11eb-99ce-2d826ce4393b.png)

Proposed (rough):
![Screen Shot 2021-01-06 at 6 15 09 PM](https://user-images.githubusercontent.com/5695990/103842961-cbfc2200-504b-11eb-90ac-84084a437949.png)

**Comment by juanfabrega** [comment]
Nice -- I Like this. We'll put it in the backlog.

**Comment by juanfabrega** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Adjust FileUpload for mobile](https://trello.com/c/UNSvArHI/876-adjust-fileupload-for-mobile)
