### ISSUE TITLE
Passing "type=button" property to an anchor link when rendering a Button as link

### ISSUE THREAD

**Issue by nathanyoung** [palmetto/palmetto-components#384]
repro

```
<Button as="a" href="/example">example</Button>
```

There is an extraneous `type="button" property on the anchor tag that gets rendered.

<img width="874" alt="Screen Shot 2021-01-15 at 9 19 47 AM" src="https://user-images.githubusercontent.com/1447339/104758284-0c763280-5713-11eb-9e69-19f874357676.png">

**Comment by syedmazharaliraza** [comment]
Hi Nathan, I would like to fix this issue. Can you assign me on this? also please provide some more info/guidance regarding the same. Thank you
