### ISSUE TITLE
Modals with inputs get covered by onscreen keyboard on mobile devices

### ISSUE THREAD

**Issue by nathanyoung** [palmetto/palmetto-components#394]
https://user-images.githubusercontent.com/1447339/106338374-8268b680-6248-11eb-9142-29734dd9dcca.MP4

**Comment by mtblanton** [comment]
see https://blog.opendigerati.com/the-eccentric-ways-of-ios-safari-with-the-keyboard-b5aa3f34228d

**Comment by juanfabrega** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Modals with inputs getting covered by keyboard](https://trello.com/c/ip3cJ3DT/877-modals-with-inputs-getting-covered-by-keyboard)

**Comment by nathanyoung** [comment]
I believe this should be fixed with this change: https://github.com/palmetto/palmetto-components/pull/673

Here's an example with the updated package.

https://user-images.githubusercontent.com/1447339/155006792-f68ea41e-4136-4e27-81cc-c73c62685387.MP4
