### ISSUE TITLE
Using the Button as an anchor as a react-router-dom component causes browswer refresh

### ISSUE THREAD

**Issue by nathanyoung** [palmetto/palmetto-components#400]
Repro:

https://codesandbox.io/s/link-component-n7tjn?file=/src/App.js

Instead of being "spa" like, the link causes a hard refresh, causing any state to be lost.

**Comment by juanfabrega** [comment]
Relevant issue in react-router repo: https://github.com/ReactTraining/react-router/issues/7761

reviewing solutions and will follow-up when I have some options.

**Comment by juanfabrega** [comment]
@nathanyoung also created a fork of your sandbox to show that the exact same thing happens with the most vanilla component wrapped in Link. 

https://codesandbox.io/s/link-component-forked-6c9dj

The issue above already did this, but just wanted to 100% rule out our Button component as a culprit here.

**Comment by juanfabrega** [comment]
Hey look another one!

https://github.com/ReactTraining/react-router/issues/7727
