### ISSUE TITLE
FormikTextInput should work with numbers without blasting the console

### ISSUE THREAD

**Issue by jchull** [palmetto/palmetto-components#420]
It does actually work fine, but many warnings are emitted in the console.

```Warning: Failed prop type: Invalid prop `field.value` of type `number` supplied to `FormikTextInput`, expected `string`.```
--removed stack trace--

```Warning: Failed prop type: Invalid prop `type` of value `number` supplied to `ForwardRef`, expected one of ["text","password","email","tel","url","search"].
    in ForwardRef (created by FormikTextInput)```
--removed stack trace--

**Comment by juanfabrega** [comment]
addressed here: https://github.com/palmetto/palmetto-components/pull/422
