### ISSUE TITLE
Time input in Request Design modal throws error in focus

### ISSUE THREAD

**Issue by shgiebner21** [palmetto/palmetto-components#424]
When moving from the Date modal to the Time input field, the user is kicked out of the Time input and an error is thrown.
The user has to click in the Time input a second time to be able to select a time.
<img width="599" alt="Screen Shot 2021-03-09 at 3 26 53 PM" src="https://user-images.githubusercontent.com/22160449/110536665-b8267800-80ef-11eb-8e1d-c40ca5ff027c.png">

**Comment by nathanyoung** [comment]
repro video: 

https://user-images.githubusercontent.com/1447339/110551482-734c1280-80ea-11eb-8053-5d655106a4f8.mov

**Comment by juanfabrega** [comment]
Hey @shgiebner21 this issue has been addressed in our latest release. Note that this includes a change to the `DateInput` component whereby it no longer has a toplevel `onBlur` event, but. If there are any questions about how this might affect any existing implementations please let me know. You can see our recommended approach in the docs here:

https://ux.palmetto.com/?path=/docs/components-dateinput-overview--input-blur-event
