### ISSUE TITLE
Box Component gives RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by nick-at-work** [palmetto/palmetto-components#454]
Using a Box with `v0.68.0`, I get this error:

![image](https://user-images.githubusercontent.com/73852955/115811433-4eb7ab80-a3b5-11eb-956b-e0896132e432.png)

```
RangeError: Maximum call stack size exceeded
at index.js:2
    at Array.findIndex (<anonymous>)
    at findMatchingBreakpoint (index.js:2)
    at findMatchingBreakpoint (index.js:2)
    at findMatchingBreakpoint (index.js:2)
```

I'm using this in https://github.com/palmetto/github-action-stats:

```js
<Box as="div" childGap="sm" direction="col" display="flex">
  <div style={{ width: '100%', maxWidth: 800 }}>
    {chartData && <Bar data={generateRunData(runData, chartData)} getElementAtEvent={getElementAtEvent} width={320} height={200} options={options} />}
  </div>
</Box>
```

If I change it to:
```js
<Box childGap="sm" >
   ...
```

It renders fine. I have the same Box sibling earlier that doesn't have this issue. I haven't investigated much more at the moment since I'm just prototyping stuff.

**Comment by nathanyoung** [comment]
try changing ` direction="col"` to `direction="column"`

**Comment by nathanyoung** [comment]
btw, not sure if that's the cause, just something i noticed.

**Comment by nick-at-work** [comment]
> try changing ` direction="col"` to `direction="column"`

That appears to have been the cause, thanks!
