### ISSUE TITLE
3 new components for the home app

### ISSUE THREAD

**Issue by RyanMacBern** [palmetto/palmetto-components#463]
We have 3 frequently used components in the app that would be useful to make available for prototypes. The easiest route would be to add these to palmetto-components. It might make sense to keep them in a separate app-only sub-package if possible.

1. [OptionButton](https://master--5ff883f14dba3500210f7296.chromatic.com/?path=/story/components-optionbutton--default) as used on [Account](https://master--5ff883f14dba3500210f7296.chromatic.com/?path=/story/pages-account--default), [Onboarding](https://master--5ff883f14dba3500210f7296.chromatic.com/?path=/story/pages-onboarding--default), and [Summary](https://master--5ff883f14dba3500210f7296.chromatic.com/?path=/story/pages-onboardingconfirmation-summary--with-reject) pages
2. [OptionTile](https://master--5ff883f14dba3500210f7296.chromatic.com/?path=/story/components-optiontile--selected) as used on [Services](https://ux-prototype.palmetto.com/app/services), [PalmettoProtect](https://master--5ff883f14dba3500210f7296.chromatic.com/?path=/story/pages-account-subscriptions-palmettoprotect--default), and [Checkout](https://master--5ff883f14dba3500210f7296.chromatic.com/?path=/story/pages-account-subscriptions-palmettoprotect-checkout--default) pages
3. [RadioGroup](https://master--5ff883f14dba3500210f7296.chromatic.com/?path=/story/components-radiogroup--default) as used on [Connect](https://master--5ff883f14dba3500210f7296.chromatic.com/?path=/story/pages-connect--started), [PreferredLanguage](https://master--5ff883f14dba3500210f7296.chromatic.com/?path=/story/pages-onboarding-preferredlanguage--default), [TreeRemoval](https://master--5ff883f14dba3500210f7296.chromatic.com/?path=/story/pages-onboarding-treeremoval--default), and [HomeownersAssociation](https://master--5ff883f14dba3500210f7296.chromatic.com/?path=/story/pages-onboarding-homeownersassociation--default) pages

**Comment by RyanMacBern** [comment]
It makes more sense to make these components available from a separate repository. See https://trello.com/c/RNBAh95D/917-export-app-components-for-use-in-prototype. Closing this issue.

**Comment by juanfabrega** [comment]
Hey @RyanMacBern we actually are in the process if integrating these into the component library (starting with the radio/option tiles). 

It will likely be released in the next day or 2. I'll chat with @nathanyoung to get his thoughts on the remaining ones, but figured it might be slightly more awkward to have the app serve up a components package.

**Comment by RyanMacBern** [comment]
@juanfabrega Oh great! I hadn't seen any action on this, so I thought I'd remove the burden from UX. We should chat about how we want to handle things like this going forward.

**Comment by nathanyoung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Radio Group (tile/card)  palmetto-app](https://trello.com/c/FNHT5OuX/646-radio-group-tile-card-palmetto-app)

**Comment by nathanyoung** [comment]
@juanfabrega reminder to tag @RyanMacBern on the PR

**Comment by nathanyoung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Option Button (palmetto app)](https://trello.com/c/lREcHqSK/643-option-button-palmetto-app)

**Comment by nathanyoung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Option Tile (palmetto app) (card?)](https://trello.com/c/P1dL9JGn/644-option-tile-palmetto-app-card)
