### ISSUE TITLE
Error received when including an extra space in a padding or margin prop hard to diagnose

### ISSUE THREAD

**Issue by mtblanton** [palmetto/palmetto-components#476]
Small thing!

when I pass a `padding` prop like `padding="0 lg 0 0 "` with an extra space at the end I get this error: `TypeError: Cannot read property '0' of undefined`.

it'd be nice to have this typechecked (maybe with template literal types? https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html), enforced in the code, or just have it show a more friendly error message!

can probably repro with:
```
<Box padding="0 lg 0 0 ">test</Box>
```

**Comment by juanfabrega** [comment]
@mtblanton will evaluate our options here and get back to you on this, thanks @mtblanton

**Comment by nathanyoung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Minor bugs](https://trello.com/c/6KAmKTHK/685-minor-bugs)

**Comment by juanfabrega** [comment]
Hey @mtblanton I've been exploring this and ran into 2 main issues with the template literal types. Although if there is a better way to do this I'd appreciate your feedback.

The approach I took was to create a generic `CssShorthand<T extends string>` type that can then be used to create specific types that follow the format of 1, 2, 3, or 4 single space separated values.

For example, padding and margin would use `type BaseSpacing = CssShorthand<SpacingSize>`

This did the job quite well in terms of type checking string values in the component like this:

```jsx
// TS error
<Box margin="md       md" />

// TS error
<Box margin="md randomText" />

// NO TS error
<Box margin="md md" />
```

However it failed in two places:
FIrst off, it is not working properly with template strings even if the variables share the type that is passed to the generic
```jsx
const verticalMargin = 'md' as SpacingSize;

// Type 'string' is not assignable to type '"base" | "0" | "5xl" | etc...
<Box margin={`${verticalMargin} lg`} />
```

secondly, it seems the number of permutations is just too large (around 40,000), so TS complains with this all over the place:

`Expression produces a union type that is too complex to represent.`

Unless there is a more performant alternative, I think I will simply add an error message for devs to warn them in the console.

**Comment by mtblanton** [comment]
Error message in the console sounds good!
