### ISSUE TITLE
FormikSelectInput Throws Validation Error Upon First Selection; on Mobile Only

### ISSUE THREAD

**Issue by JCarmine** [palmetto/palmetto-components#482]
We seem to have a bug with FormikSelectInput where it errors in some instances even though a valid selection was made. This is what I’ve found so far:

1. It only happens on mobile viewports, not desktop.
2. I suspect that the user-agent has something to do with it.
3. Once in an error state, toggling the dropdown again and making another selection results in no error.
4. It’s happening in both logistics and palmetto-component’s Formik example.
5. It only happens on SelectInput; not SelectInputNative.

![Screen Shot 2021-05-20 at 1 59 57 PM](https://user-images.githubusercontent.com/5695990/119755686-4096f800-be57-11eb-9c52-0dd43462ea98.png)

**Comment by juanfabrega** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [FormikSelectInput validation error on mobile](https://trello.com/c/bwsgdIdQ/880-formikselectinput-validation-error-on-mobile)
