### ISSUE TITLE
Create full page layouts as visual test stories

### ISSUE THREAD

**Issue by juanfabrega** [palmetto/palmetto-components#490]
It would be helpful as part of our visual testing suite, to have full page layouts that utilize lots of components interacting with each other, and act as a canary of sorts to spot any discrepancies generated by new commits. E.G: A dashboard page, a contact page, etc.

These could most likely be lifted straight from the alchemy ux prototype, with dummy data feeding it.

**Comment by nathanyoung** [comment]
https://trello.com/c/kKbiKz5k/610-storybook-and-chromatic-stories-for-logistics-platform

**Comment by juanfabrega** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create full page layout examples](https://trello.com/c/TJ5M9xhf/881-create-full-page-layout-examples)
