### ISSUE TITLE
Should we make the type prop for TextInput required?

### ISSUE THREAD

**Issue by JCarmine** [palmetto/palmetto-components#493]
As it currently is, the `type` prop is not required and defaults to "text". The main problem that we are seeing in logistics with this is that folks are forgetting to pass the type prop for email, phone, etc. This in turn results in mobile users getting the wrong keyboard when they interact with the non-text fields.

While making this change will be more cumbersome for the developer, it will ensure that they are forced to think about what `type` the field actually is, and ultimately result in a better experience for mobile users.

Of course, `type` is not required in the html spec, and defaults to "text". However, this spec was written before the time of mobile. 

Also, could we be more explicit about what strings `type` excepts in Storybook? It might save someone the hassle of going to Mozilla.

**Comment by juanfabrega** [comment]
hey @JCarmine while I agree this can lead to the proper type being omitted, I'd rather leave it up to individual teams to decide on the correct approach here.
