### ISSUE TITLE
DateInput component exception

### ISSUE THREAD

**Issue by marciaga** [palmetto/palmetto-components#495]
I noticed the `DateInput` component will throw an exception if there's no label for the `TextInput` component it contains. 

Steps to reproduce: 
* Add `hideLabel: true` to `textInputProps`
* Tap the input field to bring up the `Popover` containing the `DatePicker` 
* Tap outside the `Popover`
* Exception is thrown: `Cannot read property 'children' of undefined`.

Live example of behavior: https://codesandbox.io/s/hardcore-rosalind-cobcf

**Comment by juanfabrega** [comment]
Hey @marciaga this is now addressed by this PR: https://github.com/palmetto/palmetto-components/pull/499

and included in the latest release 0.74.4.
