### ISSUE TITLE
SelectInput label appears disconnected from select element w/ helpText

### ISSUE THREAD

**Issue by adepatie** [palmetto/palmetto-components#510]
![image](https://user-images.githubusercontent.com/5141091/121721926-cb602f80-cab2-11eb-899f-cb318f822605.png)

The SelectInput components label has additional margin on the bottom that creates a disconnect when helpText is present. Removing the `.select-input-label` class should be enough to resolve this.

**Comment by nathanyoung** [comment]
This doesn't appear to be happening in our example documentation. https://ux.palmetto.com/?path=/docs/components-selectinputnative-overview--help-text#help-text

Can you link a page that shows this?

**Comment by adepatie** [comment]
@nathanyoung This was opened by mistake. I see that that there is a reset override int he project I'm working on that I didn't notice at first. Sorry!

**Comment by adepatie** [comment]
@nathanyoung This could be handled in the component library by explicitly setting the margin to '0' for help text. It's the override that is causing the issue I'm having but adding to this library would prevent it for others as well.
