### ISSUE TITLE
SelectInput's value overlaps with down arrow when value is long

### ISSUE THREAD

**Issue by JCarmine** [palmetto/palmetto-components#527]
I've seen this a few times now. Would it be possible to restrict the width of the value's container and use `text-overflow: ellipsis;`?

![Screen Shot 2021-07-13 at 1 25 52 PM](https://user-images.githubusercontent.com/5695990/125539553-d7a14098-1cac-4ced-be1e-d93d40ebd8ce.png)

**Comment by juanfabrega** [comment]
@JCarmine thanks for bringing this one up, definitely needs to be addressed, I will get it in the queue and take care of it asap.

**Comment by nathanyoung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SelectInput's value overlaps with down arrow when value is long](https://trello.com/c/bkxfOVgy/780-selectinputs-value-overlaps-with-down-arrow-when-value-is-long)

**Comment by juanfabrega** [comment]
@JCarmine this is now fixed, however, please note that adding `text-overflow: ellipsis` on select elements isn't very straightforward and in most cases requires either a fixed pixel width or javascript, so I decided to scrap it for the time being with a simple cutoff before the dropdown arrow.
