### ISSUE TITLE
Webpack 5 warning for exporting named imports from json files

### ISSUE THREAD

**Issue by dg-harris** [palmetto/palmetto-components#534]
When bundling with webpack 5, we're seeing the following warnings:

warn  - ./node_modules/@palmetto/palmetto-components/dist/palmetto-components.esm.js
Should not import the named export 'size'.'breakpoint' (imported as 'size') from default-exporting module (only default export is available soon)

./node_modules/@palmetto/palmetto-components/dist/palmetto-components.esm.js
Should not import the named export 'color'.'brand' (imported as 'color') from default-exporting module (only default export is available soon)

./node_modules/@palmetto/palmetto-components/dist/palmetto-components.esm.js
Should not import the named export 'size'.'z-index' (imported as 'size') from default-exporting module (only default export is available soon)

**Comment by nathanyoung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Webpack 5 warning for exporting named imports from json files](https://trello.com/c/YBtNkTsH/830-webpack-5-warning-for-exporting-named-imports-from-json-files)
