### ISSUE TITLE
childGap on Box not Correct when using `direction="row-reverse"`

### ISSUE THREAD

**Issue by JCarmine** [palmetto/palmetto-components#562]
Bottom margin is still applied to all but the last item (in the DOM order), even when `row-reverse` is used. Since the DOM order of the elements never changes (but the visual order does), this will result in the first visual item never having bottom margin, and the last visual item having bottom margin when it shouldn't.

![Screen Shot 2021-08-12 at 8 54 51 AM](https://user-images.githubusercontent.com/5695990/129593690-0c4a64ab-4af2-4977-bc24-dd3a7adb6fb7.png)

**Comment by juanfabrega** [comment]
Hi @JCarmine we do have some literature in the docs addressing this, and the reality is that the implementation is just to resource intensive at the moment. 

The docs addressing this also include an recommendation for an alternative, albeit it is not as easy and convenient as the childGap.

https://ux.palmetto.com/?path=/docs/components-box-overview--flex-direction
