### ISSUE TITLE
TabSlider Width/Postition not correct sometimes

### ISSUE THREAD

**Issue by mtblanton** [palmetto/palmetto-components#566]
Width/position of the TabSlider is strange sometimes when coming to the review page of DTC.

Dan Friesen and Paarul Bansal may be able to give more repro info.

Related card:
https://trello.com/c/37iYjtsu/1521-loan-cash-toggle-control-looks-broken-initially-when-cash-is-chosen

![image](https://user-images.githubusercontent.com/2118649/129807666-05dbf69c-7881-4e0d-8768-30668082e69e.png)

**Comment by nathanyoung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [TabSlider Width/Position not correct sometimes](https://trello.com/c/dKN4glOB/855-tabslider-width-position-not-correct-sometimes)
