### ISSUE TITLE
Export utility functions

### ISSUE THREAD

**Issue by allison-strandberg** [palmetto/palmetto-components#614]
We're working on an [Ember JS](https://emberjs.com/) port of this component library. We're reimplementing the components to account for the differences between Ember and React, but the utility functions in https://github.com/palmetto/palmetto-components/tree/main/src/lib should be usable as-is. Our current approach is to copy and paste these functions into our app, but we'd like to be able to consume them from palmetto-components instead. Can these functions be exported?

cc @waissbluth @b-lackner

**Comment by waissbluth** [comment]
Thanks @juanfabrega!
