### ISSUE TITLE
Export tokens for consumers

### ISSUE THREAD

**Issue by allison-strandberg** [palmetto/palmetto-components#617]
We'd like to import tokens from `src/lib/tokens.ts` such as `BASE_BRAND_COLORS` into our Ember port of this component library. This feature request is similar to https://github.com/palmetto/palmetto-components/issues/614.

Could you take a look at this, @juanfabrega? Thank you!

**Comment by juanfabrega** [comment]
understood @allison-strandberg -- Let me chat with @nathanyoung about this and we will get back to you ASAP.
