### ISSUE TITLE
Modal scrolls to first anchor in content

### ISSUE THREAD

**Issue by RyanMacBern** [palmetto/palmetto-components#628]
When a modal with a large amount of content is opened (The Terms & Agreements modal for the Palmetto App for example), if there is an anchor in the content, the modal is scrolled to that anchor. We want to prevent this behavior in the Palmetto App. The Reach Dialog has an [initialFocusRef](https://reach.tech/dialog#dialog-initialfocusref) prop that should (hopefully) allow us to target the container div as the focus in order to prevent scrolling. However, when using this prop on the Modal component it has no effect.

**Comment by juanfabrega** [comment]
@RyanMacBern any chance you can post a codesandbox reproducing the issue where the `initialFocusRef` has no effect?
