### ISSUE TITLE
Container with childGap prop added applies margin to bottom of a child element, even if it's the only child

### ISSUE THREAD

**Issue by JCarmine** [palmetto/palmetto-components#656]
To fix, I believe that the last child should never have a bottom margin applied to it: 

![Screen Shot 2021-12-28 at 5 09 58 PM](https://user-images.githubusercontent.com/5695990/147618560-74b81375-e80d-4146-9d6a-62b4105300e2.png)

**Comment by nathanyoung** [comment]
@JCarmine Can you link to the page so we can look at the dom? Want to make sure there isn't a sibling of the button that's hidden, because we can't repro this. 

If you can repro here, that would help
https://codesandbox.io/s/childgap-repro-bug-154k4?file=/src/MyComponent.js

**Comment by JCarmine** [comment]
Issue is visible on main

**Comment by JCarmine** [comment]
Issue was caused by a bug in BuildPartner; closing.
