### ISSUE TITLE
SelectInput produces warning about UNSAFE_componentWillReceiveProps in strict mode

### ISSUE THREAD

**Issue by taylorhummon** [palmetto/palmetto-components#697]
I'm seeing a warning in my console log,
```
Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. ...
```
when I'm using react's strict mode: `<React.StrictMode>`.

This appears to be caused by the `react-select`'s `<Select>` component and was resolved in v4:
https://github.com/JedWatson/react-select/issues/4094

Best,
Ben

**Comment by benhummon** [comment]
Actually, v4 of `react-select` also emits warnings for strict mode:
https://github.com/JedWatson/react-select/issues/4068

This one, at least, is fixed in v5.

It's occurring to me that we may not support React StrictMode. If that's the case, sorry for the noise.
