### ISSUE TITLE
Radio Button Group Input

### ISSUE THREAD

**Issue by nathanyoung** [palmetto/palmetto-components#74]
Radio button component that allows users to select a single option from a list of options.

```jsx
function RadioExample() {
  const [value, setValue] = React.useState("1");
  return (
    <RadioInput
      name="size"
      title="Pick Your Size"
      description="Pick your t-shirt size"
      onChange={e => setValue(e.target.value)}
      options={[
        { value: 'chocolate', label: 'Chocolate' },
        { value: 'strawberry', label: 'Strawberry' },
        { value: 'vanilla', label: 'Vanilla' },
      ]}
      value={value}
    />
  );
}
```

RadioInput Props
| prop  | type | default value |  description |
| ------------- | ------------- | ------------- | ------------- |
| name  | string |  | name attribute that gets applied to all radios |
| className | string |  | additional classNames to add to the group |
| error | bool,string |  | render the radio group in an error state and/or display a validation message |
| onChange | func | undefined | callback function |
| title | node |  | text used as the title for the group of radios |
| description | node |  | help text beneath the title |
| options | array |  | the radio buttons |
| isRequired | bool |  | at least one option must be selected |
| value | string, number|  | value of the radio to be 'checked' |

Radio Props
| prop  | type | default value |  description |
| ------------- | ------------- | ------------- | ------------- |
| name  | string |  | name attribute that gets applied to all radios |
| id | string |  | additional classNames to add to the group |
| value | bool,string |  | value that is returned on form submission |
| isChecked | func |  | if the radio is checked |
| defaultIsChecked | node |  | initially checked if true |
| isDisabled | bool |  | disable selecting the radio |
| error | bool, string |  | render the radio in an error state and/or display a validation message |
| onChange | node |  | callback when input state changes |

**Comment by nathanyoung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Radio Button/Group](https://trello.com/c/3UZwSS0D/110-radio-button-group)

**Comment by JCarmine** [comment]
Noticed that we have both `value` and `defaultValue` as props. Should there be a mode prop for this, or should it be strictly controlled?

All other inputs are strictly controlled, so we might as well follow suit.

**Comment by nathanyoung** [comment]
@JCarmine let's do strictly controlled for now

**Comment by JCarmine** [comment]
Done.
