### ISSUE TITLE
Vertical Alignment Issue in PanelSummary of Accordion

### ISSUE THREAD

**Issue by JCarmine** [palmetto/palmetto-components#789]
If a caret is rendered, and the fontSize is set to something ridiculous like 2xl, a vertical alignment issue becomes more obvious. The solution is to apply `align-items: center` to the parent of the caret and copy, but this isn’t really possible with the current API.

To Reproduce: https://app-next.palmetto.com/contacts/43232

![Screen Shot 2022-06-14 at 12 10 08 PM](https://user-images.githubusercontent.com/5695990/173671345-99c20162-de40-43e8-aa12-8370b2fad0b9.png)

**Comment by nathanyoung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Vertical Alignment Issue in PanelSummary of Accordion](https://trello.com/c/97KTvD5Q/1309-vertical-alignment-issue-in-panelsummary-of-accordion)
