### ISSUE TITLE
CSS Architecture

### ISSUE THREAD

**Issue by juanfabrega** [palmetto/palmetto-components#95]
**PROBLEM STATEMENT**
We are hoping to implement CSS architecture that enables a great development experience for both library developers and consumers. 

**BASIC REQUIREMENTS**
* [As a consumer] - Styles in the palmetto-components library should not clash with styles in my application. E.G: We should not be styling all `<input>` elements, just ours.
* [As a consumer] -- I'd like both dark and light themes available to me, and the ability to easily switch between the two.
* [As a developer] -- I'd like to write CSS easily without unknowingly introducing breaking changes to unrelated parts of the library.
* [As a developer] -- I would like our styles to be scalable and provide some avenue for DRY extensibility.
* [As a developer] -- I would like changes to our design tokens to be propagated systemically across our components (DRY implementation)
* [As a consumer] -- The component library should work for me without SASS/SCSS installed, or any kind of CSS transforms in place.

**OVERVIEW OF INITIAL TECH OPTIONS BROUGHT FORTH**
* CSS Modules (https://github.com/css-modules/css-modules)
* BEM (http://getbem.com/)
* Styled Components (https://styled-components.com/)

**Comment by juanfabrega** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CSS Architecture](https://trello.com/c/5l1ILieN/116-css-architecture)

**Comment by nathanyoung** [comment]
https://github.com/palmetto/palmetto-components/pull/120
